## Data Science Principles with Applications on Educational Data, Spring 2026
## HW1
### Due date: 05/11/2026

### Student ID: 114998411
### Name: 黃子奇 Purit Hongjirakul

##### This homework set is to practice some common operations for the exploration on the data set and be familiar with the notebook environment. Please go through each question to provide your answer. In the meantime, we use the famous iris data set as an example for your reference. First, please load the working dataset "exam_results" provided with .csv format.

### Use `pandas.read_csv('file_path')` to load the dataset
Please use the **exam_results.csv** as the dataset for **df** parameter

In [17]:
import pandas as pd
import seaborn as sns
iris = sns.load_dataset('iris')

# Load the dataset from the file path
df = pd.read_csv('exam_results.csv')

### Use `(pandas_dataset).info()` to show the dataset information

In [18]:
# Example
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


Please use the **df** as the dataset to show the dataset information

In [19]:
# Write Answer here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1734 entries, 0 to 1733
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   school          1734 non-null   int64  
 1   year            1734 non-null   int64  
 2   semester        1734 non-null   int64  
 3   grade           1734 non-null   int64  
 4   class           1734 non-null   int64  
 5   number          1734 non-null   int64  
 6   student_number  1734 non-null   int64  
 7   sex             1734 non-null   object 
 8   chinese_1       1722 non-null   float64
 9   chinese_2       1722 non-null   float64
 10  chinese_3       1476 non-null   float64
 11  math_1          1729 non-null   float64
 12  math_2          1729 non-null   float64
 13  math_3          1482 non-null   float64
 14  english_1       1727 non-null   float64
 15  english_2       1727 non-null   float64
 16  english_3       1480 non-null   float64
 17  science_1       1722 non-null   f

###  Check for missing values
- df.isna().sum()
-  df.notnull()

In [20]:
# Example 1
iris.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [21]:
# Example 2
iris.notnull()

,sepal_length,sepal_width,petal_length,petal_width,species
0,True,True,True,True,True
1,True,True,True,True,True
2,True,True,True,True,True
3,True,True,True,True,True
4,True,True,True,True,True
...,...,...,...,...,...
145,True,True,True,True,True
146,True,True,True,True,True
147,True,True,True,True,True
148,True,True,True,True,True


Please use the **df** as the dataset and check for missing values

In [22]:
# Write Answer here
df.isna().sum()

school              0
year                0
semester            0
grade               0
class               0
number              0
student_number      0
sex                 0
chinese_1          12
chinese_2          12
chinese_3         258
math_1              5
math_2              5
math_3            252
english_1           7
english_2           7
english_3         254
science_1          12
science_2          12
science_3         258
society_1           7
society_2           7
society_3         254
dtype: int64

In [23]:
df.notnull()

,school,year,semester,grade,class,number,student_number,sex,chinese_1,chinese_2,...,math_3,english_1,english_2,english_3,science_1,science_2,science_3,society_1,society_2,society_3
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1729,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1730,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1731,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1732,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True


### Use `(pandas_dataset).describe()` to show the statistical summary

In [24]:
# Example
iris.describe()

,sepal_length,sepal_width,petal_length,petal_width
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000


Please use the **df** as the dataset to show the statistical summary

In [25]:
# Write Answer here
df.describe()

,school,year,semester,grade,class,number,student_number,chinese_1,chinese_2,chinese_3,...,math_3,english_1,english_2,english_3,science_1,science_2,science_3,society_1,society_2,society_3
count,1734.000000,1734.000000,1734.000000,1734.000000,1734.000000,1734.000000,1734.000000,1722.000000,1722.000000,1476.000000,...,1482.000000,1727.000000,1727.000000,1480.000000,1722.000000,1722.000000,1476.000000,1727.000000,1727.000000,1480.000000
mean,2.163783,110.195502,1.426759,7.809689,1.209343,9.183391,10951.311995,70.584785,71.391986,71.180217,...,61.551282,65.352635,64.870874,65.952703,71.519744,68.174216,70.949864,69.701795,70.862768,68.848649
std,1.313406,1.184806,0.494749,0.794237,0.406957,6.185985,119.763954,17.183328,17.083729,17.521049,...,26.066613,24.019259,24.021116,23.197664,19.927029,20.565307,20.010341,18.895631,18.902483,18.843150
min,1.000000,108.000000,1.000000,7.000000,1.000000,1.000000,10801.000000,8.000000,0.000000,10.000000,...,0.000000,10.000000,5.000000,11.000000,4.000000,0.000000,0.000000,4.000000,14.000000,13.000000
25%,1.000000,109.000000,1.000000,7.000000,1.000000,4.000000,10820.000000,60.000000,61.000000,61.000000,...,42.000000,45.000000,45.000000,47.000000,58.000000,54.000000,58.000000,57.000000,58.000000,56.750000
50%,2.000000,110.000000,1.000000,8.000000,1.000000,8.000000,10918.000000,74.000000,74.000000,75.000000,...,66.000000,69.000000,69.000000,70.000000,74.000000,70.000000,74.000000,72.000000,74.000000,71.000000
75%,3.000000,111.000000,2.000000,8.000000,1.000000,13.000000,11027.000000,84.000000,85.000000,85.000000,...,83.000000,86.000000,86.000000,86.000000,88.000000,85.000000,88.000000,85.000000,86.000000,84.000000
max,5.000000,112.000000,2.000000,9.000000,2.000000,28.000000,11241.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000


### Data Cleaning
- remove null - `(pandas_dataset).dropna()`
- remove duplicated data - `(pandas_dataset).drop_duplicates()`
- remove unecessary columns  - `(pandas_dataset).drop(columns=['col1', 'col2'])`

Example : Use `iris.drop_duplicates()`

In [26]:
# Example
iris.drop_duplicates()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


Please use `df.drop_duplicates()`

In [27]:
# Write Answer here
df.drop_duplicates()

,school,year,semester,grade,class,number,student_number,sex,chinese_1,chinese_2,...,math_3,english_1,english_2,english_3,science_1,science_2,science_3,society_1,society_2,society_3
0,1,108,1,7,1,1,10801,Female,84.0,85.0,...,100.0,94.0,98.0,96.0,86.0,90.0,93.0,71.0,99.0,92.0
1,1,108,1,7,1,2,10802,Female,86.0,80.0,...,64.0,87.0,92.0,89.0,81.0,79.0,96.0,87.0,89.0,90.0
2,1,108,1,7,1,3,10803,Female,74.0,82.0,...,78.0,94.0,97.0,97.0,78.0,83.0,93.0,68.0,98.0,67.0
3,1,108,1,7,1,4,10804,Female,78.0,69.0,...,50.0,71.0,66.0,74.0,80.0,61.0,89.0,71.0,87.0,57.0
4,1,108,1,7,1,5,10805,Female,52.0,72.0,...,29.0,41.0,46.0,62.0,73.0,60.0,69.0,48.0,66.0,73.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1729,5,112,1,7,1,3,11203,Female,67.0,64.0,...,43.0,51.0,54.0,64.0,54.0,48.0,66.0,58.0,60.0,68.0
1730,5,112,1,7,1,4,11204,Female,73.0,72.0,...,32.0,44.0,37.0,39.0,68.0,56.0,82.0,59.0,73.0,70.0
1731,5,112,1,7,1,5,11205,Female,88.0,76.0,...,45.0,65.0,51.0,58.0,70.0,58.0,60.0,59.0,64.0,73.0
1732,5,112,1,7,1,6,11206,Female,78.0,85.0,...,70.0,71.0,76.0,61.0,64.0,76.0,52.0,79.0,73.0,73.0


### Use `(pandas_dataset).query()` to query the data

Example : Query thedata with `species == "virginica"` from 'iris' dataset

In [28]:
# example
iris.query('species == "virginica"').head()

,sepal_length,sepal_width,petal_length,petal_width,species
100,6.3,3.3,6.0,2.5,virginica
101,5.8,2.7,5.1,1.9,virginica
102,7.1,3.0,5.9,2.1,virginica
103,6.3,2.9,5.6,1.8,virginica
104,6.5,3.0,5.8,2.2,virginica


Please query the data with `year == 109` from 'df' dataset

In [29]:
# Write Answer here
df.query('year == 109').head()

,school,year,semester,grade,class,number,student_number,sex,chinese_1,chinese_2,...,math_3,english_1,english_2,english_3,science_1,science_2,science_3,society_1,society_2,society_3
52,1,109,1,8,1,1,10801,Female,85.0,91.0,...,85.0,100.0,99.0,95.0,96.0,76.0,84.0,82.0,75.0,91.0
53,1,109,1,8,1,2,10802,Female,91.0,89.0,...,62.0,94.0,77.0,87.0,97.0,76.0,80.0,87.0,86.0,98.0
54,1,109,1,8,1,3,10803,Female,89.0,80.0,...,94.0,95.0,90.0,91.0,97.0,84.0,84.0,92.0,72.0,91.0
55,1,109,1,8,1,4,10804,Female,82.0,78.0,...,46.0,56.0,52.0,57.0,81.0,62.0,64.0,60.0,68.0,76.0
56,1,109,1,8,1,5,10805,Female,75.0,75.0,...,21.0,30.0,27.0,44.0,76.0,62.0,62.0,54.0,58.0,81.0


### 5. Use `(pandas_dataset).columns` to show column names

In [30]:
# Example
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

Please use the **df** as the dataset and show the column names

In [31]:
# Write Answer here
df.columns

Index(['school', 'year', 'semester', 'grade', 'class', 'number',
       'student_number', 'sex', 'chinese_1', 'chinese_2', 'chinese_3',
       'math_1', 'math_2', 'math_3', 'english_1', 'english_2', 'english_3',
       'science_1', 'science_2', 'science_3', 'society_1', 'society_2',
       'society_3'],
      dtype='object')

### 6. Change column name - `(pandas_dataset).rename(columns={  },inplace=True)`
Example : rename the column name from **species** to **Type** - `'species':'Type'`

In [32]:
# Example
iris.rename(columns={'species':'Type'},inplace=True)
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'Type'], dtype='object')

Please rename the column name in **df** dataset

from **number** to **inclass_number** - `'number':'inclass_number'`  
from **year** to **academic_year** - `'year':'academic_year'`

In [33]:
# Write Answer here
df.rename(columns={'number':'inclass_number', 'year':'academic_year'}, inplace=True)
df.columns

Index(['school', 'academic_year', 'semester', 'grade', 'class',
       'inclass_number', 'student_number', 'sex', 'chinese_1', 'chinese_2',
       'chinese_3', 'math_1', 'math_2', 'math_3', 'english_1', 'english_2',
       'english_3', 'science_1', 'science_2', 'science_3', 'society_1',
       'society_2', 'society_3'],
      dtype='object')

### 7. Query after rename column
Please query the data with `academic_year == 111`

(Do this after question 6. is done)

In [34]:
# Write Answer here
df.query('academic_year == 111').head()

,school,academic_year,semester,grade,class,inclass_number,student_number,sex,chinese_1,chinese_2,...,math_3,english_1,english_2,english_3,science_1,science_2,science_3,society_1,society_2,society_3
280,1,111,1,9,1,1,10901,Female,98.0,93.0,...,98.0,100.0,98.0,100.0,92.0,86.0,94.0,98.0,96.0,98.0
281,1,111,1,9,1,2,10902,Female,81.0,80.0,...,90.0,74.0,66.0,75.0,74.0,86.0,78.0,81.0,84.0,73.0
282,1,111,1,9,1,3,10903,Female,63.0,74.0,...,92.0,95.0,75.0,81.0,66.0,64.0,80.0,69.0,75.0,61.0
283,1,111,1,9,1,4,10904,Female,80.0,84.0,...,75.0,79.0,66.0,76.0,62.0,62.0,66.0,80.0,85.0,73.0
284,1,111,1,9,1,5,10905,Female,39.0,64.0,...,38.0,30.0,26.0,29.0,26.0,36.0,30.0,35.0,40.0,37.0
